# Generated by Django 3.0.9 on 2021-04-06 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('flowering_time', models.DateField(blank=True, null=True)),
                ('harvest_time', models.DateField(blank=True, null=True)),
                ('perennial', models.BooleanField(blank=True, null=True)),
                ('hardy', models.BooleanField(blank=True, null=True)),
                ('location_type', models.CharField(blank=True, choices=[('Sc', 'Schatten'), ('H', 'Halbschatten'), ('So', 'Sonne')], max_length=2, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('plant_type', models.CharField(choices=[('O', 'Obst'), ('G', 'Gemüse'), ('Z', 'Zierpflanze'), ('K', 'Kraut')], max_length=1)),
                ('market_type', models.CharField(choices=[('V', 'Verschenken'), ('T', 'Tauschen')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reserved', models.BooleanField(default=False)),
                ('city', models.CharField(max_length=30)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', related_query_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plant',
                'verbose_name_plural': 'Plants',
                'ordering': ['created_at', 'title'],
                'index_together': {('title', 'slug')},
            },
        ),
    ]
