# Generated by Django 3.0.9 on 2020-08-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='plant',
            unique_together={('title', 'slug')},
        ),
    ]
