# Generated by Django 3.0.9 on 2020-08-07 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0002_auto_20200807_1417'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plant',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='plant',
            index_together={('title', 'slug')},
        ),
    ]
